#!/bin/bash

flatpak install flathub com.brave.Browser -y

flatpak install flathub com.heroicgameslauncher.hgl -y

flatpak install flathub com.valvesoftware.Steam -y

flatpak install flathub net.davidotek.pupgui2 -y

flatpak install flathub com.github.johnfactotum.Foliate -y

flatpak install flathub com.github.tchx84.Flatseal -y


